name: SurvivalEngine
version: '${project.version}'
main: me.einjojo.survivalengine.SurvivalEngine
api-version: 1.18
authors: [ Ein_Jojo ]
description: Just improving the overall survival feeling
commands:
  get:
    description: Admin command
  team:
    aliases:
      - teams
    description: Manage your team.
  difficulty:
    aliases:
      - schwierigkeit
    description: Change the difficulty for a period of time
  teleporter:
    description: Zeige deine Teleporter auf.
  stats:
    description: Zeige die Stats über andere Spieler
  fix:
    description: Repariere kaputte Kristalle
  waypoint:
    description: Waypoint Management